import '../styles/globals.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { Playfair_Display } from 'next/font/google'
import HeaderIcon from '@/components/HeaderIcon'
import { SpeedInsights } from "@vercel/speed-insights/next"
 
const playfair = Playfair_Display({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})


export const metadata = {
  title: 'Resistance SAS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body className={playfair.className}>
        <Navbar />
        <HeaderIcon />
        {children}
        <Footer />
        </body>
    </html>
  )
}